name: functional_zipper
description: A library implementing functional zippers following Huet's paper.
version: 0.0.2
repository: https://github.com/fmardini/zipper

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
